export { default as Eleventy } from './11ty.svelte';
export { default as Gatsby } from './Gatsby.svelte';
export { default as Gridsome } from './Gridsome.svelte';
export { default as Hugo } from './Hugo.svelte';
export { default as Jekyll } from './Sapper.svelte';
export { default as NextJS } from './NextJS.svelte';
export { default as NuxtJS } from './NuxtJS.svelte';
export { default as Sapper } from './Sapper.svelte';
export { default as SvelteKit } from './SvelteKit.svelte';
