[build]
command = "npm run build"
publish = "dist"

[dev]
command = "npm run start"

[[plugins]]
package = "netlify-plugin-a11y"

[[plugins]]
package = "netlify-plugin-subfont"

[[redirects]]
from = "https://navillus.nl/*"
to = "https://navillus.dev/*"
status = 301
force = true
