[build]
    command = "yarn build"
    publish = "dist"

[dev]
    command = "yarn start"

[[plugins]]
    package = "netlify-plugin-a11y"

[[plugins]]
    package = "netlify-plugin-cache-folder"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200

[[redirects]]
    from = "https://navillus.nl"
    to = "https://navillus.dev"
    status = 301
    force = true

[[redirects]]
    from = "https://navillus.nl/"
    to = "https://navillus.dev/"
    status = 301
    force = true

[[redirects]]
    from = "https://navillus.nl/*"
    to = "https://navillus.dev/:splat"
    status = 301
    force = true
