[build]
command = "npm run build"
publish = "build"

[dev]
command = "npm run start"

[[plugins]]
package = "netlify-plugin-a11y"

[[plugins]]
package = "@netlify/plugin-sitemap"

[[plugins]]
package = "netlify-plugin-checklinks"
