[build]
    command = "yarn build"
    publish = "dist"

[dev]
    command = "yarn start"

[[plugins]]
    package = "netlify-plugin-a11y"

[[plugins]]
    package = "netlify-plugin-cache-folder"

[[headers]]
    for = "/*"
    [headers.values]
        Content-Security-Policy = "default-src 'self' https://cdn.usefathom.com; script-src 'self' 'unsafe-inline' https://cdn.usefathom.com"
        X-Content-Security-Policy = "default-src 'self' https://cdn.usefathom.com; script-src 'self' 'unsafe-inline' https://cdn.usefathom.com"
        X-WebKit-CSP = "default-src 'self' https://cdn.usefathom.com; script-src 'self' 'unsafe-inline' https://cdn.usefathom.com"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200

[[redirects]]
    from = "https://navillus.nl"
    to = "https://navillus.dev"
    status = 301
    force = true

[[redirects]]
    from = "https://navillus.nl/"
    to = "https://navillus.dev/"
    status = 301
    force = true

[[redirects]]
    from = "https://navillus.nl/*"
    to = "https://navillus.dev/:splat"
    status = 301
    force = true