---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Admin
- type: document
  path: src/data/site.json
  label: Site Settings
- type: document
  path: src/data/navigation.json
  label: Navigation
- type: heading
  label: Content
- type: directory
  path: src/data/authors
  label: Authors
  create: documents
  match: "*"
  new_doc_ext: json
  templates:
  - author
- type: directory
  path: src/data/pages
  label: Pages
  create: documents
  match: "*"
  templates:
  - hero-page
  - legal-page
- type: directory
  path: src/data/pages/blog
  label: Blog Posts
  create: documents
  match: "*"
  templates:
  - blog-post-page
upload_dir: public/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
