name: Trigger Netlify Build
on:
  schedule:
    # Every day at midnight
    - cron: '0 0 * * *'
jobs:
  build:
    name: Netlify Build
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -s -X POST -d {} "${HOOK}"
        env:
          HOOK: ${{ secrets.NETLIFY_CRON_BUILD_HOOK }}